package im.fdx.v2ex.daogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import im.fdx.v2ex.model.MemberModel;

import im.fdx.v2ex.daogen.MemberModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memberModelDaoConfig;

    private final MemberModelDao memberModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memberModelDaoConfig = daoConfigMap.get(MemberModelDao.class).clone();
        memberModelDaoConfig.initIdentityScope(type);

        memberModelDao = new MemberModelDao(memberModelDaoConfig, this);

        registerDao(MemberModel.class, memberModelDao);
    }
    
    public void clear() {
        memberModelDaoConfig.clearIdentityScope();
    }

    public MemberModelDao getMemberModelDao() {
        return memberModelDao;
    }

}
