# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "(bundle)Deploy a internal version to the Google Play"
  lane :internal do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'internal',
     skip_upload_metadata: true,
     skip_upload_screenshots: true,
     skip_upload_images: true,
      )
  end

  desc "(bundle)Deploy a new version to production the Google Play"
  lane :prod do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'production',
     skip_upload_metadata: true,
     skip_upload_screenshots: true,
     skip_upload_images: true,
     skip_upload_apk: true,
      )
  end

  desc "promote to production"
  lane :promote do
    upload_to_play_store(track: 'internal',
         track_promote_to: 'production',
         track_promote_release_status: 'completed',
         version_code: ,
         skip_upload_metadata: true,
         skip_upload_screenshots: true,
         skip_upload_images: true,
         skip_upload_changelogs: true
         )
  end

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end
end
